In [1]:
import pymysql 
from sqlalchemy import create_engine

In [2]:
engine= create_engine("mysql+pymysql://root:yourpassword@localhost/Ironhack")

In [3]:
import pandas as pd

In [16]:
table1 = pd.read_sql('select Date, Départements, cas_confirmes,deces,reanimation,hospitalises from Cas_covid',engine)

In [20]:
table2=pd.read_sql('select*from Offres', engine)

In [33]:
table3 = pd.read_sql('select Départements,cas_confirmes,deces,reanimation,hospitalises, Date from Cas_covid left join Offres on trimestre = Date',engine)

In [34]:
table3

,Départements,cas_confirmes,deces,reanimation,hospitalises,Date
0,Ain,943.0,67.0,88.0,550.0,2020-03-31
1,Aisne,436.0,778.0,376.0,1384.0,2020-03-31
2,Allier,188.0,38.0,31.0,244.0,2020-03-31
3,Alpes-Maritimes,1096.0,145.0,221.0,1040.0,2020-03-31
4,Alpes-de-Haute-Provence,90.0,3.0,20.0,116.0,2020-03-31
...,...,...,...,...,...,...
702,Vendée,0.0,12617.0,90.0,693.0,2021-09-30
703,Vienne,0.0,11585.0,55.0,396.0,2021-09-30
704,Vosges,0.0,36958.0,52.0,1573.0,2021-09-30
705,Yonne,0.0,25371.0,151.0,2357.0,2021-09-30
706,Yvelines,0.0,79640.0,905.0,5443.0,2021-09-30